DATES:
  starting_date: "2021-01-01"
  ending_date: "2023-12-31"

WEATHER:
  variables:
    precipitation: 
      mission: chirps
      source: chirps
      
    solar_radiation: 
      mission: agera5
      source: agera5

    temperature_tmax:
      mission: agera5
      source: agera5

    temperature_tmin:
      mission: agera5
      source: agera5

    vapour_pressure:
      mission: agera5
      source: agera5

    wind_speed:
      mission: agera5
      source: agera5
    
    reference_evapotranspiration:
      mission: agera5
      source: agera5

SPATIAL_INFO:
  spatial_file: null
  extent: [-61.9, 15.7, -61, 16.6]

GENERAL:
  suffix: 'guadalupe'
  ncores: 10
  task: datacube # download
  reference_variable: 'precipitation'
  export_as_netcdf: False

PATHS:
  output_path: "weather/"